name: Kustomize Diff

on:
  pull_request:
  push:
  workflow_dispatch:

permissions:
  contents: write
  pull-requests: write

jobs:
  kustomize-diff:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          ref: ${{ github.head_ref }}

      - name: Install kustomize
        run: |
          curl -s "https://raw.githubusercontent.com/kubernetes-sigs/kustomize/master/hack/install_kustomize.sh" | bash
          sudo mv kustomize /usr/local/bin/kustomize
          kustomize version

      - name: Save kustomize build output for feature branch
        run: |
          find . -name kustomization.yaml -execdir kustomize build \; > feature-branch-output.yaml

      - name: Checkout main branch
        run: |
          git fetch origin main
          git checkout main

      - name: Save kustomize build output for main branch
        run: |
          find . -name kustomization.yaml -execdir kustomize build \; > main-branch-output.yaml

      - name: Show kustomize diff
        run: |
          git diff --quiet --output kustomize-diff.txt -U10 main-branch-output.yaml feature-branch-output.yaml
          cat kustomize-diff.txt

      - name: Post diff as PR comment
        if: github.event_name == 'pull_request'
        uses: actions/github-script@v6
        with:
          script: |
            const fs = require('fs');
            const diff = fs.readFileSync('kustomize-diff.txt', 'utf8');
            const issue_number = context.issue.number;
            const body = `### Kustomize Diff\n\`\`\`diff\n${diff}\n\`\`\``;

            github.issues.createComment({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number,
              body
            });