name: Kustomize Diff

on:
  pull_request:
  # push:
  workflow_dispatch:

permissions:
  contents: write
  pull-requests: write

jobs:
  kustomize-diff:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          ref: ${{ github.head_ref }}

      - name: Install kustomize
        run: |
          curl -s "https://raw.githubusercontent.com/kubernetes-sigs/kustomize/master/hack/install_kustomize.sh" | bash
          sudo mv kustomize /usr/local/bin/kustomize
          kustomize version

      - name: Save kustomize build output for feature branch
        run: |
          find . -name kustomization.yaml -execdir kustomize build \; > /tmp/feature-branch-output.yaml

      - name: Save kustomize build output for feature branch per file
        run: |
          ORG_PATH=$(pwd)
          find . -name kustomization.yaml -execdir sh -c '
            FILE_PATH=${ORG_PATH/$(pwd)}
            output_file="/tmp/feature/$(FILE_PATH)/kustomization.yaml"
            mkdir -p "/tmp/feature/$(FILE_PATH)"
            kustomize build . > "$output_file"
          ' {} \;

      - name: Checkout main branch
        run: |
          git fetch origin main
          git checkout main

      - name: Save kustomize build output for main branch
        run: |
          find . -name kustomization.yaml -execdir kustomize build \; > /tmp/main-branch-output.yaml

      - name: Save kustomize build output for main branch per file
        run: |
          ORG_PATH=$(pwd)
          find . -name kustomization.yaml -execdir sh -c '
            FILE_PATH=${ORG_PATH/$(pwd)}
            output_file="/tmp/main/$(FILE_PATH)/kustomization.yaml"
            mkdir -p "/tmp/main/$(FILE_PATH)"
            kustomize build . > "$output_file"
          ' {} \;

      - name: Show kustomize diff
        run: |
          ### mv /tmp/feature-branch-output.yaml ./feature-branch-output.yaml
          diff -U10 /tmp/main-branch-output.yaml /tmp/feature-branch-output.yaml > kustomize-diff.txt || true

      - name: Show kustomize diff folder
        run: |
          diff -bur /tmp/main /tmp/feature > kustomize-diff-dir.txt || true

      - name: Post diff as PR comment
        uses: actions/github-script@v6
        with:
          script: |
            const fs = require('fs');
            const diff = fs.readFileSync('kustomize-diff.txt', 'utf8');
            const issue_number = context.issue.number;
            const commentIdentifier = "### Kustomize Diff";
            const body = `${commentIdentifier}\n\`\`\`diff\n${diff}\n\`\`\``;

            const { data: comments } = await github.rest.issues.listComments({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: issue_number
            });

            const comment = comments.find(comment => comment.user.type === 'Bot' && comment.body.startsWith(commentIdentifier));

            if (comment) {
              await github.rest.issues.updateComment({
                owner: context.repo.owner,
                repo: context.repo.repo,
                comment_id: comment.id,
                body: body
              });
            } else {
              await github.rest.issues.createComment({
                owner: context.repo.owner,
                repo: context.repo.repo,
                issue_number: issue_number,
                body: body
              });
            }

      - name: Post diff as PR comment dir
        uses: actions/github-script@v6
        with:
          script: |
            const fs = require('fs');
            const diff = fs.readFileSync('kustomize-diff-dir.txt', 'utf8');
            const issue_number = context.issue.number;
            const commentIdentifier = "### Kustomize Diff Dir";
            const body = `${commentIdentifier}\n\`\`\`diff\n${diff}\n\`\`\``;

            const { data: comments } = await github.rest.issues.listComments({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: issue_number
            });

            const comment = comments.find(comment => comment.user.type === 'Bot' && comment.body.startsWith(commentIdentifier));

            if (comment) {
              await github.rest.issues.updateComment({
                owner: context.repo.owner,
                repo: context.repo.repo,
                comment_id: comment.id,
                body: body
              });
            } else {
              await github.rest.issues.createComment({
                owner: context.repo.owner,
                repo: context.repo.repo,
                issue_number: issue_number,
                body: body
              });
            }
### Update existing PR comment instead of creating a new one
### create mulitple kustomize files instead of one